language: python
python:
- "3.5"
cache: pip
install: "pip install -r requirements.txt -r requirements/test.txt"
services:
- postgresql
before_script:
- "lathermail > log_lathermail.txt 2>&1 &"
- psql -c 'CREATE DATABASE blueworld;' -U postgres
- psql -c "CREATE USER blueworld with password 'blueworld'" -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE blueworld TO blueworld;' -U postgres
- "python manage.py collectstatic --noinput"
- python manage.py makemigrations
- python manage.py migrate
- psql -c 'ALTER SEQUENCE join_bagtype_id_seq RESTART 5;' blueworld
- psql -c "COPY join_bagtype(id,name,active,display_order) from '$PWD/data/bag_type.csv' with csv;" blueworld
- psql -c "COPY join_bagtypecostchange(bag_type_id,changed,weekly_cost) from '$PWD/data/bag_type_cost_change.csv' with csv;" blueworld
- psql -c "COPY join_collectionpoint(name,location,latitude,longitude,active,display_order,collection_day) from '$PWD/data/collection_point.csv' with csv" blueworld
- echo "from django.contrib.auth.models import User; User.objects.create_superuser('superuser', 'james@example.com', '123123ab')" | python manage.py shell
- echo "from django.contrib.auth.models import User, Permission; user=User.objects.create_user('staff', password='123123ab', email='staff@example.com'); user.is_staff=True; user.user_permissions.add(Permission.objects.get(name='Can add collection point')); user.user_permissions.add(Permission.objects.get(name='Can change collection point')); user.user_permissions.add(Permission.objects.get(name='Can add bag type')); user.user_permissions.add(Permission.objects.get(name='Can change bag type')); user.user_permissions.add(Permission.objects.get(name='Can add bag type cost change')); user.user_permissions.add(Permission.objects.get(name='Can change customer')); user.user_permissions.add(Permission.objects.get(name='Can add customer tag')); user.user_permissions.add(Permission.objects.get(name='Can change customer tag')); user.save(); exit();" | python manage.py shell
- echo "from django.contrib.sites.models import Site; s = Site.objects.get(id=1); s.domain='localhost'; s.name='BlueWorld'; s.save()" | python manage.py shell
- "python manage.py runserver 0.0.0.0:8000 > log_runserver.txt 2>&1 &"
- "curl -0 -H 'X-Mail-Password: password' http://127.0.0.1:5000/api/0/messages/"
- sleep 5
script: behave --tags=-chrome
after_script:
- cat log_runserver.txt
- cat log_lathermail.txt
