language: python
python:
- "3.5"
cache: pip
install: "pip install -r requirements.txt -r requirements/test.txt"
services:
- postgresql
before_script:
- "lathermail > log_lathermail.txt 2>&1 &"
- psql -c 'CREATE DATABASE blueworld;' -U postgres
- psql -c "CREATE USER blueworld with password 'blueworld'" -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE blueworld TO blueworld;' -U postgres
- "python manage.py collectstatic --noinput"
- python manage.py makemigrations
- python manage.py migrate
- echo "from django.contrib.auth.models import User; User.objects.create_superuser('superuser', 'james@3aims.com', '123123ab')" | python manage.py shell
- echo "from django.contrib.sites.models import Site; s = Site.objects.get(id=1); s.domain='localhost'; s.name='BlueWorld'; s.save()" | python manage.py shell
- "python manage.py runserver 0.0.0.0:8000 > log_runserver.txt 2>&1 &"
- "curl -0 -H 'X-Mail-Password: password' http://127.0.0.1:5000/api/0/messages/"
- sleep 8
script: behave
after_script:
- cat log_runserver.txt
- cat log_lathermail.txt
