language: python
python:
- "3.5"
cache: pip
install: "pip install -r requirements.txt -r requirements/dev.txt"
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE blueworld;' -U postgres
- psql -c "CREATE USER blueworld with password 'blueworld'" -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE blueworld TO blueworld;' -U postgres
- python manage.py makemigrations
- python manage.py migrate
- echo "from django.contrib.auth.models import User; User.objects.create_superuser('superuser', 'james@3aims.com', '123123ab')" | python manage.py shell
- python manage.py runserver 0.0.0.0:8000 &
script: behave
