language: python
python:
- "3.5"
install: "pip install -r requirements.txt -r requirements/dev.txt"
env:
- DJANGO_SETTINGS_MODULE=blueworld.settings
- DATABASE_URL=postgres://blueworld-lite:blueworld-lite@localhost:5432/blueworld-lite
- DEBUG=True
- EMAIL_BACKEND=django.core.mail.backends.locmem.EmailBackend
- DEFAULT_FROM_EMAIL=no-reply@blueworld.example.com
- SERVER_EMAIL=error@blueworld.example.com
services:
- postgresql
before_script:
- python manage.py runserver
- psql -c 'CREATE DATABASE "blue-world-lite";' -U postgres
- psql -c 'CREATE USER "blue-world-lite" with password \'blue-world-lite\';' -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE "blueworld-lite" TO "blueworld-lite";' -U postgres
- python manage.py makemigrations
- python manage.py migrate
- echo "from django.contrib.auth.models import User; User.objects.create_superuser('superuser', 'james@3aims.com', '123123ab')" | python manage.py shell
script: rm -r test_dir; behave
