language: python
addons:
  postgresql: "9.4"
python:
- "3.5"
cache: pip
install: "pip install -r requirements.txt -r requirements/test.txt"
services:
- postgresql
before_script:
- "lathermail > log_lathermail.txt 2>&1 &"
- psql -c 'CREATE DATABASE blueworld;' -U postgres
- psql -c "CREATE USER blueworld with password 'blueworld';" -U postgres
- psql -c "ALTER USER blueworld CREATEDB;" -U postgres
- "python manage.py collectstatic --noinput"
- python manage.py makemigrations
- python manage.py migrate
- python manage.py loaddata data/user.json
- python manage.py loaddata data/initial.json
- "python manage.py runserver 0.0.0.0:8000 > log_runserver.txt 2>&1 &"
- "curl -0 -H 'X-Mail-Password: password' http://127.0.0.1:5000/api/0/messages/"
- sleep 5
script: python billing_week.py && python manage.py test --failfast && behave --tags=-chrome --no-capture
after_script:
- cat log_runserver.txt
- cat log_lathermail.txt
