# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BagQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g. 'Standard veg'.", max_length=50)),
                ('weekly_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the weekly fee for receiving this bag.', max_digits=12, null=True, verbose_name='Weekly cost')),
                ('display_order', models.IntegerField(blank=True, help_text='Bags will be sorted by this number (though they will always be grouped into fruit or veg first)', null=True)),
                ('active', models.BooleanField(default=True, help_text='Active bags appear in the joining form.')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'The Old Fire Station'. <b>IMPORTANT</b>: Due to a limitation you <b>cannot use non-standard characters like accents</b> - sorry. If you do, you form will not display and you might get a strange error.", max_length=40)),
                ('location', models.CharField(blank=True, help_text="E.g. 'Leswin Road, N16'", max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, help_text="Allows your pickup to show on a map. Latitude should be between 49 and 60 in the UK. You can find latitude and longitude by following these instructions: <ol><li>Go to <a href='http://maps.google.co.uk/' target='_NEW'>Google maps</a></li><li>Click the tiny green flask icon on the top-right</li><li>Scroll down and enable the 'LatLng Tool Tip'</li><li>Find your pickup and zoom in close</li><li>You'll see (latitude, longitude) showing on the mouse pointer</li><li>Note them down and copy latitude into the field above and longitude into the field below</li></ol>", null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude should be between -10 and 2 in the UK', null=True)),
                ('active', models.BooleanField(default=True, help_text='You can mark this pickup as not available at the moment if you need to')),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPointChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.CollectionPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('go_cardless', models.CharField(default='', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='collectionpointchange',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.Customer'),
        ),
        migrations.AddField(
            model_name='bagquantity',
            name='bag_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.BagType'),
        ),
        migrations.AddField(
            model_name='bagquantity',
            name='order_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.OrderChange'),
        ),
    ]
