# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('LEFT', 'Left'), ('ACTIVE', 'Active'), ('HOLD', 'Hold')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='accountstatuschange',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.Customer'),
        ),
    ]
