# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_auto_20160623_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='started',
        ),
        migrations.AlterField(
            model_name='accountstatuschange',
            name='status',
            field=models.CharField(choices=[('AWAITING_DIRECT_DEBIT', 'Awating Go Cardless'), ('AWAITING_START_CONFIRMATION', 'Awating Start Confirmation'), ('ACTIVE', 'Active'), ('HOLD', 'On Hold'), ('LEFT', 'Left')], max_length=255),
        ),
    ]
