# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_auto_20160623_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagTypeCostChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('weekly_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the weekly fee for receiving this bag.', max_digits=12, null=True, verbose_name='Weekly cost')),
            ],
        ),
        migrations.RemoveField(
            model_name='bagtype',
            name='weekly_cost',
        ),
        migrations.AddField(
            model_name='bagtypecostchange',
            name='bag_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.BagType'),
        ),
    ]
