# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_auto_20160816_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagtype',
            name='tag_color',
            field=models.CharField(blank=True, default='', help_text='String used on the pick up list for the bag colour', max_length=50, null=True),
        ),
    ]
