# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_auto_20160704_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BagQuantity',
            new_name='CustomerOrderChangeBagQuantity',
        ),
        migrations.AlterModelOptions(
            name='customerorderchangebagquantity',
            options={'verbose_name_plural': 'customer order change bag quantities'},
        ),
    ]
