# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_auto_20160825_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='instructions',
            field=models.TextField(blank=True, help_text='If you have specific instructions for accessing the bags, add them here, so users can see them in email or their dashboard', null=True),
        ),
    ]
