# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_auto_20160704_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorderchangebagquantity',
            options={'verbose_name_plural': 'customer order changes bag quantities'},
        ),
    ]
