# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_auto_20160704_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionpoint',
            options={'ordering': ['-active', 'display_order']},
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='name',
            field=models.CharField(help_text="e.g. 'The Old Fire Station'. <b>IMPORTANT</b>: Due to a limitation you <b>cannot use non-standard characters like accents</b> - sorry. If you do, you form will not display and you might get a strange error.", max_length=40, unique=True),
        ),
    ]
