# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0008_auto_20160704_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagtype',
            name='name',
            field=models.CharField(help_text="E.g. 'Standard veg'.", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='name',
            field=models.CharField(help_text="e.g. 'The Old Fire Station'", max_length=40, unique=True),
        ),
    ]
