# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0009_auto_20160704_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='accountstatuschange',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_status_change', to='join.Customer'),
        ),
        migrations.AlterField(
            model_name='accountstatuschange',
            name='status',
            field=models.CharField(choices=[('AWAITING_DIRECT_DEBIT', 'Awating Go Cardless'), ('ACTIVE', 'Active'), ('LEFT', 'Left')], max_length=255),
        ),
        migrations.AlterField(
            model_name='customerorderchangebagquantity',
            name='customer_order_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_quantities', to='join.CustomerOrderChange'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(to='join.CustomerTag'),
        ),
    ]
