# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0010_auto_20160704_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertag',
            options={'ordering': ('tag',)},
        ),
        migrations.RenameField(
            model_name='customertag',
            old_name='title',
            new_name='tag',
        ),
    ]
