# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0011_auto_20160704_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='active',
            field=models.BooleanField(default=True, help_text='You can mark this pickup as not available if you need to. This might be because it is full for example.'),
        ),
    ]
