# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0013_auto_20160705_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagtypecostchange',
            name='bag_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_changes', to='join.BagType'),
        ),
    ]
