# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0014_auto_20160706_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagtype',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='\n        Bags will be sorted by this number.\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='active',
            field=models.BooleanField(default=True, help_text='\n        You can mark this pickup as not available if you need to. This might\n        be because it is full for example.\n        '),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='latitude',
            field=models.FloatField(blank=True, help_text="\n        Allows your pickup to show on a map. Latitude should be\n        between 49 and 60 in the UK. You can find latitude and longitude by\n        following these instructions: <ol><li>Go to <a\n        href='http://maps.google.co.uk/' target='_NEW'>Google\n        maps</a></li><li>Click the tiny green flask icon on the\n        top-right</li><li>Scroll down and enable the 'LatLng Tool\n        Tip'</li><li>Find your pickup and zoom in close</li><li>You'll see\n        (latitude, longitude) showing on the mouse pointer</li><li>Note them\n        down and copy latitude into the field above and longitude into the\n        field below</li></ol>\n        ", null=True),
        ),
    ]
