# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0016_collectionpoint_inactive_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='inactive_reason',
            field=models.CharField(choices=[('FULL', 'Full'), ('CLOSING_DOWN', 'Closing down')], default='FULL', max_length=255, null=True),
        ),
    ]
