# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0017_auto_20160708_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='go_cardless',
        ),
        migrations.AddField(
            model_name='customer',
            name='gocardless_mandate_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='gocardless_redirect_flow_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='gocardless_session_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
