# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0018_auto_20160718_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount_pence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BillingGoCardlessMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(default='', max_length=255)),
                ('gocardless_redirect_flow_id', models.CharField(default='', max_length=255)),
                ('gocardless_mandate_id', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gocardless_mandate_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gocardless_redirect_flow_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gocardless_session_token',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='join.CustomerTag'),
        ),
        migrations.CreateModel(
            name='BillingSkipCredit',
            fields=[
                ('billingcredit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='join.BillingCredit')),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('join.billingcredit',),
        ),
        migrations.AddField(
            model_name='billingcredit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_credit', to='join.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gocardless_current_mandate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='join.BillingGoCardlessMandate'),
        ),
    ]
