# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0019_auto_20160720_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggocardlessmandate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='go_cardless_mandate', to='join.Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gocardless_current_mandate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_use_for_customer', to='join.BillingGoCardlessMandate'),
        ),
    ]
