# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0021_auto_20160721_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance_carried_over',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='holiday_due',
            field=models.IntegerField(default=0),
        ),
    ]
