# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0022_auto_20160722_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip', to='join.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='billingskipcredit',
            name='billingcredit_ptr',
        ),
        migrations.AlterField(
            model_name='accountstatuschange',
            name='status',
            field=models.CharField(choices=[('AWAITING_DIRECT_DEBIT', 'Awating Go Cardless'), ('ACTIVE', 'Active'), ('LEFT', 'Left')], max_length=255),
        ),
        migrations.DeleteModel(
            name='BillingSkipCredit',
        ),
    ]
