# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0023_auto_20160725_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skip',
            name='collection_date',
            field=models.DateTimeField(),
        ),
    ]
