# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 10:12
from __future__ import unicode_literals

from django.db import migrations
from django.core.urlresolvers import reverse

class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    def create_initial_exports(app, schema_editor):
        de = app.get_model('exports.DataExport')

        mailchimp = de(
            title="Mailchimp",
            description="Weekly CSV Export, to import into the master Mailchimp list",
            export_url = reverse("mailchimp")

        ).save()

        db = de(
            title="Database Export",
            description="CSV Export of the blue world customer database",
            export_url=reverse("db")
        ).save()

        payments = de(
            title="Payments",
            description="CSV Export for all the payments made through the site",
            export_url=reverse("payments")
        ).save()

        churn = de(
            title="Churn",
            description="CSV Export for customer churn",
            export_url=reverse("churn")
        ).save()

    def remove_initial_exports(app, schema_editor):
        de = app.get_model('exports.DataExport')

        de.objects.filter(export_url=reverse("mailchimp")).delete()
        de.objects.filter(export_url=reverse("db")).delete()
        de.objects.filter(export_url=reverse("payments")).delete()
        de.objects.filter(export_url=reverse("churn")).delete()

    operations = [
        migrations.RunPython(create_initial_exports, remove_initial_exports),
    ]
